import type { Metadata } from "next";
import "@/shared/styles/globals.css";
import { Header } from "@/widgets/header";

export const metadata: Metadata = {
  title: "Sway",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`antialiased bg-background`}
        suppressHydrationWarning 
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
